### ISSUE TITLE
Upstream source strings may contain questionable data

### ISSUE THREAD

**Issue by madig** [googlefonts/aosp-test-texts#6]
1. Copy the line https://android.googlesource.com/platform/packages/apps/Gallery/+/refs/heads/master/res/values-en-rXC/strings.xml#57 into https://r12a.github.io/uniview/
2. See how the actual string is full of alternating LTR and RTL marks

![image](https://user-images.githubusercontent.com/380829/123955232-4bd2cb80-d9a1-11eb-913c-c166502849c9.png)

I think this should be fixed upstream? It causes DivisionByZeroErrors in a certain Python script. @davelab6 @chrissimpkins

**Comment by chrissimpkins** [comment]
What locale is this Niko?

**Comment by madig** [comment]
"en-rXC", whatever that is supposed to be. Googling yields nothing of interest.

**Comment by chrissimpkins** [comment]
It looks like those strings landed in the Android source with the commit message "Import translations. DO NOT MERGE". Lol.  

For the purposes of the GPOS optimization tests in Google Sans, I suggest that we filter these `*-rXC` locales out or simply ignore it if it is a very small minority of the test data and you already have a divide by zero workaround.  It looks like English of some form and we should have plenty of representative English data for testing purposes.

Agree that the JSON string glob in this repo will need to be cleaned to make it a useful resource for others.  

Re: the Android project / bugs, please do feel free to report it! :)
